env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: darwin-build
    main: ./cmd/main.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - '8'

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ title .Os }}_{{ replace .Arch "amd64" "x86_64"  }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - data/sql/migrations

release:
  disable: true

snapshot:
  name_template: "{{ incminor .Version }}-next"
